repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: python
        entry: black
        types_or: [ python, pyi ]
      - id: isort
        name: isort
        language: python
        entry: isort
        types_or: [ python, pyi ]