name: Prerelease Build
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 1
jobs:
  prerelease:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.4'
      - name: Test
        run: go test ./...
      - name: Build
        run: |
          GOOS=linux  GOARCH=amd64 go build -o out/butler-linux
          GOOS=darwin GOARCH=amd64 go build -o out/butler-darwin
      - name: Create prerelease
        uses: softprops/action-gh-release@v1
        with:
          name: prerelease
          tag_name: prerelease
          prerelease: true
          files: |
            out/butler-linux
            out/butler-darwin
