name: Prerelease Build
on:
  schedule:
    - cron: 0 0 * * 1
jobs:
  prerelease:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.4'
      - name: Test
        run: go test ./...
      - name: Build
        run: |
          GOOS=linux  GOARCH=amd64 go build -o out/butler-linux
          GOOS=darwin GOARCH=amd64 go build -o out/butler-darwin
      - run: echo "DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
      - name: Create Prerelease
        id: create-prerelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.DATE }}-prerelease
          release_name: Prerelease ${{ env.DATE }}
          draft: false
          prerelease: true
      - name: Upload Linux Prerelease Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-prerelease.outputs.upload_url }}
          asset_path: ./out/butler-linux
          asset_name: butler-linux
          asset_content_type: application/octet-stream
      - name: Upload Darwin Prerelease Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-prerelease.outputs.upload_url }}
          asset_path: ./out/butler-darwin
          asset_name: butler-darwin
          asset_content_type: application/octet-stream
