name: PreRelease Build
on:
  schedule:
    - cron: 0 0 * * 1-5
jobs:
  pre-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.4'
      - name: Test
        run: go test ./...
      - name: Build
        run: |
          GOOS=linux  GOARCH=amd64 go build -o out/butler-linux
          GOOS=darwin GOARCH=amd64 go build -o out/butler-darwin
      - name: Set Date
        run: echo "DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.DATE }}-pre-release
          release_name: Pre Release ${{ env.DATE }}
          draft: false
          prerelease: true
      - name: Upload Linux Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/butler-linux
          asset_name: butler-linux
          asset_content_type: application/zip
      - name: Upload Darwin Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/butler-darwin
          asset_name: butler-darwin
          asset_content_type: application/zip
